# Ruby Alpine is based on Alpine Linux. It's only 125Mb.
# This Dockerfile contains what is needed to run a pure Ruby
# application with Postgresql

FROM ruby:2.4.2-alpine

ADD Gemfile /app/
ADD Gemfile.lock /app/
RUN apk add --no-cache bash gawk sed grep bc coreutils vim
RUN apk add --update ruby-dev build-base git \
    libxml2-dev libxslt-dev pcre-dev libffi-dev \
    postgresql-dev

RUN gem install bundler --no-ri --no-rdoc && \
    cd /app && bundle install

RUN apk del ruby-dev build-base

ADD . /app
RUN chown -R nobody:nogroup /app
USER nobody
ENV RACK_ENV development

WORKDIR /app
