FROM ruby:2.2-alpine

RUN apk add --no-cache git build-base \
      curl-dev imagemagick-dev postgresql-dev \
      libxml2-dev libxslt-dev tzdata nodejs \
      bash ghostscript postgresql

RUN mkdir /app
WORKDIR /app

RUN echo "gem: --no-rdoc --no-ri" > .gemrc

RUN gem install nokogiri -v 1.6.6.2 -- --use-system-libraries
RUN bundle config build.libv8 --with-system-v8

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install

ADD . /app

RUN mkdir -p log && \
    mkdir -p tmp/cache \
    mkdir -p tmp/pids \
    mkdir -p tmp/sessions \
    mkdir -p tmp/sockets
