FROM ruby:2.4.2-alpine
ADD Gemfile /app/
ADD Gemfile.lock /app/

RUN apk --update add --virtual build-dependencies ruby-dev build-base git libxml2-dev libxslt-dev pcre-dev libffi-dev postgresql-dev&& \ 
    gem install bundler --no-ri --no-rdoc && \
    cd /app ; bundle install --without development test && \
    apk del build-dependencies

ADD . /app

RUN chown -R nobody:nogroup /app
USER nobody

ENV RACK_ENV development

EXPOSE 3000

WORKDIR /app
